import 'dart:math';

class SemanticDistanceEngine {
  final Random _random = Random();

  static const Map<String, String> _clusterMap = {
    'APPLE': 'FOOD',
    'COFFEE': 'FOOD',
    'BREAD': 'FOOD',
    'OCEAN': 'NATURE',
    'FOREST': 'NATURE',
    'DESERT': 'NATURE',
    'WINTER': 'NATURE',
    'RAIN': 'NATURE',
    'MOUNTAIN': 'NATURE',
    'RIVER': 'NATURE',
    'FLOWER': 'NATURE',
    'STORM': 'NATURE',
    'SPACE': 'COSMOS',
    'MOON': 'COSMOS',
    'SUN': 'COSMOS',
    'FIRE': 'ENERGY',
    'MUSIC': 'CULTURE',
    'BOOK': 'CULTURE',
    'CASTLE': 'HISTORY',
    'DOCTOR': 'HEALTH',
    'CLOCK': 'OBJECTS',
    'HOUSE': 'OBJECTS',
    'BIRD': 'ANIMALS',
    'DOG': 'ANIMALS',
    'CAT': 'ANIMALS',
    'FISH': 'ANIMALS',
    'GOLD': 'MINERALS',
    'BRIDGE': 'INFRASTRUCTURE',
    'TRAIN': 'TRANSPORT',
    'AIRPLANE': 'TRANSPORT',
    'MONEY': 'ECONOMY',
  };

  final List<SemanticDistancePuzzle> _puzzles = [
    SemanticDistancePuzzle(
      target: 'APPLE',
      relatedWords: {
        'FRUIT': 10.5,
        'RED': 12.4,
        'GREEN': 13.5,
        'CORE': 11.2,
        'SEED': 13.8,
        'PEEL': 14.0,
        'WORM': 16.5,
        'IPHONE': 15.8,
        'JUICE': 18.2,
        'PIE': 20.3,
        'TREE': 22.1,
        'ORANGE': 25.2,
        'BANANA': 30.1,
        'ORCHARD': 28.5,
        'TECH': 40.5,
        'CIDER': 14.5,
        'CRISP': 16.0,
        'SWEET': 17.0,
        'BITE': 18.0,
        'RIPE': 19.0,
        'SAUCE': 19.5,
        'CRUNCH': 20.0,
        'FOOD': 21.0,
        'TART': 21.0,
        'STEM': 21.5,
        'TASTE': 22.0,
        'CRUMBLE': 22.5,
        'DELICIOUS': 23.0,
        'BAKE': 24.0,
        'BLOSSOM': 24.5,
        'CINNAMON': 25.0,
        'BRANCH': 26.0,
        'CARAMEL': 26.5,
        'HARVEST': 27.0,
        'FARM': 29.0,
        'GROVE': 29.5,
        'MACINTOSH': 15.0,
        'FUJI': 15.5,
        'GALA': 16.0,
        'GRANNY': 17.5,
        'HONEYCRISP': 14.8,
      },
    ),
    SemanticDistancePuzzle(
      target: 'OCEAN',
      relatedWords: {
        'WATER': 5.2,
        'SEA': 8.1,
        'TIDE': 9.5,
        'WAVE': 12.3,
        'PACIFIC': 12.0,
        'ATLANTIC': 12.5,
        'SHORE': 13.5,
        'COAST': 14.0,
        'SURF': 14.5,
        'UNDERWATER': 15.0,
        'BEACH': 15.4,
        'MARINE': 16.0,
        'SAND': 16.0,
        'CORAL': 16.2,
        'SWIM': 16.8,
        'REEF': 17.0,
        'AQUA': 17.5,
        'CURRENT': 18.0,
        'BLUE': 18.5,
        'ISLAND': 19.0,
        'SHELL': 19.5,
        'SALT': 20.1,
        'DIVER': 20.5,
        'DEPTH': 21.0,
        'SHIP': 21.5,
        'SAIL': 22.0,
        'FISH': 22.4,
        'MARITIME': 22.5,
        'NAUTICAL': 23.0,
        'BOAT': 23.0,
        'DOLPHIN': 24.0,
        'SUBMARINE': 24.5,
        'OCTOPUS': 25.0,
        'SAILOR': 25.5,
        'DEEP': 25.6,
        'ABYSS': 26.0,
        'ANCHOR': 26.0,
        'CRAB': 26.5,
        'SEAFLOOR': 27.0,
        'TSUNAMI': 28.0,
        'STORM': 28.5,
        'TRENCH': 29.0,
        'SHARK': 30.2,
        'WHALE': 32.1,
      },
    ),
    SemanticDistancePuzzle(
      target: 'SPACE',
      relatedWords: {
        'STAR': 10.2,
        'PLANET': 12.5,
        'COSMIC': 12.8,
        'ORBIT': 13.0,
        'SUN': 13.5,
        'MARS': 14.0,
        'UNIVERSE': 14.2,
        'MILKYWAY': 14.5,
        'GALAXY': 15.1,
        'EARTH': 15.5,
        'INTERSTELLAR': 15.8,
        'GRAVITY': 16.0,
        'SOLAR': 16.5,
        'NEBULA': 16.8,
        'SUPERNOVA': 17.0,
        'SATELLITE': 17.2,
        'ASTEROID': 17.8,
        'METEOR': 18.0,
        'MOON': 18.4,
        'LIGHTYEAR': 18.5,
        'COMET': 19.0,
        'CONSTELLATION': 19.5,
        'ASTRONOMY': 20.0,
        'ASTRONOMER': 21.0,
        'TELESCOPE': 21.5,
        'ECLIPSE': 22.0,
        'ASTRONAUT': 22.3,
        'ATMOSPHERE': 23.0,
        'SHUTTLE': 23.5,
        'VACUUM': 24.0,
        'HUBBLE': 24.0,
        'ROCKET': 25.1,
        'ALIEN': 26.0,
        'LAUNCH': 26.5,
        'CRATER': 27.0,
        'MISSION': 28.0,
        'NASA': 30.5,
        'DARK': 32.0,
        'VOID': 35.6,
        'BLACK': 40.1,
      },
    ),
    SemanticDistancePuzzle(
      target: 'FIRE',
      relatedWords: {
        'FLAME': 4.0,
        'HEAT': 6.5,
        'HOT': 7.5,
        'BURN': 8.0,
        'BLAZE': 9.0,
        'INFERNO': 9.5,
        'SMOKE': 10.0,
        'EMBER': 11.0,
        'SPARK': 11.5,
        'ASH': 12.0,
        'IGNITE': 12.5,
        'CAMPFIRE': 13.0,
        'CINDER': 13.5,
        'WARM': 14.0,
        'COALS': 14.0,
        'FLARE': 14.5,
        'MATCH': 15.0,
        'PYRE': 15.0,
        'FIREPLACE': 15.5,
        'LIGHT': 16.0,
        'KINDLE': 16.5,
        'TORCH': 17.0,
        'SOOT': 18.0,
        'GLOW': 19.0,
        'WOOD': 20.0,
        'FURNACE': 21.0,
        'EXTINGUISH': 22.0,
        'FUEL': 23.0,
        'FIREFIGHTER': 25.0,
        'DANGER': 28.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'MUSIC',
      relatedWords: {
        'SONG': 5.0,
        'MELODY': 7.0,
        'SOUND': 8.0,
        'TUNE': 8.5,
        'RHYTHM': 9.5,
        'HARMONY': 10.0,
        'SINGING': 10.5,
        'BEAT': 11.0,
        'SYMPHONY': 11.0,
        'NOTES': 11.5,
        'INSTRUMENT': 12.0,
        'VOCAL': 12.0,
        'CHORD': 12.5,
        'TEMPO': 13.0,
        'ORCHESTRA': 13.0,
        'GUITAR': 13.5,
        'DANCE': 14.0,
        'PIANO': 14.0,
        'COMPOSE': 14.5,
        'BAND': 15.0,
        'ACOUSTIC': 15.5,
        'AUDIO': 16.0,
        'CHOIR': 16.0,
        'CONCERT': 17.0,
        'TRACK': 17.5,
        'LISTEN': 18.0,
        'RECORD': 18.5,
        'ARTIST': 19.0,
        'SPEAKER': 20.0,
        'EAR': 22.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'FOREST',
      relatedWords: {
        'TREE': 5.0,
        'WOODS': 6.0,
        'WOOD': 8.0,
        'LEAVES': 9.5,
        'LEAF': 10.0,
        'NATURE': 11.0,
        'GROVE': 11.5,
        'PINE': 12.0,
        'FOLIAGE': 12.0,
        'BRANCH': 12.5,
        'OAK': 13.0,
        'TRUNK': 13.0,
        'PLANT': 13.5,
        'GREEN': 14.0,
        'TIMBER': 14.0,
        'LOG': 14.5,
        'JUNGLE': 15.0,
        'MOSS': 15.0,
        'BARK': 15.5,
        'TRAIL': 16.0,
        'CANOPY': 16.0,
        'BUSH': 16.5,
        'PARK': 17.0,
        'WILDERNESS': 17.0,
        'FERN': 17.5,
        'WILD': 18.0,
        'WILDLIFE': 18.5,
        'SHADE': 19.0,
        'HIKE': 19.5,
        'CAMP': 20.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'COFFEE',
      relatedWords: {
        'BEAN': 6.0,
        'BREW': 7.5,
        'ESPRESSO': 8.0,
        'JAVA': 8.5,
        'CAFFEINE': 9.0,
        'CAPPUCCINO': 9.0,
        'LATTE': 9.5,
        'ROAST': 10.0,
        'MUG': 10.5,
        'CUP': 11.0,
        'DECAF': 11.0,
        'MOCHA': 11.5,
        'DRINK': 12.0,
        'CAFE': 12.5,
        'AROMA': 13.0,
        'BARISTA': 13.5,
        'HOT': 14.0,
        'FROTH': 14.0,
        'DRIP': 15.5,
        'MORNING': 15.0,
        'WARM': 16.0,
        'WAKE': 16.5,
        'MILK': 17.0,
        'BITTER': 17.5,
        'TEA': 18.0,
        'ENERGY': 18.0,
        'STEAM': 18.5,
        'POUR': 19.0,
        'SUGAR': 19.5,
        'DARK': 20.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'DESERT',
      relatedWords: {
        'SAND': 5.0,
        'DRY': 6.5,
        'DUNE': 7.0,
        'HOT': 8.0,
        'HEAT': 8.5,
        'SAHARA': 8.5,
        'ARID': 9.0,
        'CACTUS': 10.0,
        'SUN': 11.0,
        'OASIS': 11.5,
        'CAMEL': 12.0,
        'DROUGHT': 13.0,
        'DUST': 14.0,
        'MIRAGE': 14.0,
        'BARREN': 15.0,
        'WARM': 15.5,
        'THIRST': 16.0,
        'DESOLATE': 17.0,
        'LIZARD': 18.0,
        'CANYON': 19.0,
        'NOMAD': 19.5,
        'ROCK': 20.0,
        'WILDERNESS': 21.0,
        'WIND': 22.0,
        'EMPTY': 23.0,
        'YELLOW': 24.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'CASTLE',
      relatedWords: {
        'KING': 6.0,
        'QUEEN': 7.0,
        'FORTRESS': 8.0,
        'PALACE': 8.5,
        'TOWER': 9.0,
        'KINGDOM': 9.0,
        'KNIGHT': 9.5,
        'DRAWBRIDGE': 9.5,
        'MOAT': 10.0,
        'KEEP': 10.0,
        'MEDIEVAL': 10.5,
        'ROYAL': 11.0,
        'RAMPART': 11.0,
        'WALL': 11.5,
        'DUNGEON': 11.5,
        'STONE': 12.0,
        'THRONE': 12.0,
        'CROWN': 13.0,
        'SIEGE': 13.0,
        'GATE': 13.5,
        'SWORD': 14.0,
        'LORD': 14.0,
        'ARMOR': 14.5,
        'BRIDGE': 15.0,
        'NOBLE': 15.5,
        'GUARD': 16.0,
        'ARCHER': 16.5,
        'ANCIENT': 18.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'WINTER',
      relatedWords: {
        'COLD': 5.0,
        'SNOW': 6.0,
        'ICE': 7.0,
        'FROZEN': 7.5,
        'FROST': 8.0,
        'FREEZE': 8.5,
        'SNOWFLAKE': 9.0,
        'BLIZZARD': 9.5,
        'SNOWMAN': 10.0,
        'CHILL': 11.0,
        'WHITE': 12.0,
        'SHIVERING': 12.0,
        'DECEMBER': 12.5,
        'SCARF': 13.0,
        'IGLOO': 13.0,
        'SLED': 13.5,
        'COAT': 14.0,
        'POLAR': 14.0,
        'MITTENS': 14.0,
        'SKI': 14.5,
        'GLOVE': 15.0,
        'GLACIER': 15.0,
        'SKATING': 15.0,
        'SEASON': 15.5,
        'HAIL': 16.0,
        'PARKA': 16.5,
        'STORM': 17.0,
        'HIBERNATE': 20.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'RAIN',
      relatedWords: {
        'WATER': 5.0,
        'WET': 6.0,
        'CLOUD': 7.0,
        'DOWNPOUR': 7.0,
        'DRIZZLE': 7.5,
        'STORM': 8.0,
        'SHOWER': 8.0,
        'PUDDLE': 8.5,
        'DROPLETS': 8.5,
        'DROP': 9.0,
        'POUR': 9.0,
        'UMBRELLA': 9.5,
        'THUNDER': 10.0,
        'MONSOON': 10.0,
        'PRECIPITATION': 10.5,
        'LIGHTNING': 11.0,
        'MOIST': 11.5,
        'DAMP': 11.0,
        'WEATHER': 12.0,
        'SPLASH': 12.5,
        'FLOOD': 13.0,
        'RAINBOW': 13.0,
        'SKY': 14.0,
        'GREY': 15.0,
        'SLICK': 16.0,
        'GLOOM': 17.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'BOOK',
      relatedWords: {
        'READ': 5.0,
        'PAGE': 6.5,
        'STORY': 7.0,
        'READER': 7.0,
        'NOVEL': 7.5,
        'CHAPTER': 8.0,
        'FICTION': 8.0,
        'AUTHOR': 8.5,
        'TALE': 8.5,
        'WORDS': 9.0,
        'LITERATURE': 9.0,
        'LIBRARY': 9.5,
        'TEXT': 10.0,
        'PLOT': 10.0,
        'WRITE': 10.5,
        'PROSE': 10.5,
        'PAPER': 11.0,
        'BOOKSTORE': 11.0,
        'BOOKMARK': 11.5,
        'COVER': 12.0,
        'POEM': 12.0,
        'VOLUME': 12.5,
        'PRINT': 13.0,
        'SHELF': 13.5,
        'SPINE': 14.0,
        'STUDY': 14.0,
        'LEARN': 15.0,
        'BOUND': 15.5,
      },
    ),
    SemanticDistancePuzzle(
      target: 'MOUNTAIN',
      relatedWords: {
        'PEAK': 5.0,
        'SUMMIT': 6.0,
        'CLIMB': 7.5,
        'HILL': 8.0,
        'EVEREST': 8.5,
        'HIGH': 9.0,
        'RIDGE': 9.0,
        'CLIFF': 9.5,
        'ELEVATION': 9.5,
        'ROCK': 10.0,
        'ALTITUDE': 10.0,
        'CRAG': 10.0,
        'SLOPE': 10.5,
        'STEEP': 10.5,
        'HIKE': 11.0,
        'ALPS': 11.0,
        'ALPINE': 11.0,
        'RANGE': 11.5,
        'SNOW': 12.0,
        'BOULDER': 12.0,
        'VALLEY': 12.5,
        'STONE': 13.0,
        'VOLCANO': 13.0,
        'TRAIL': 13.5,
        'GLACIER': 14.0,
        'NATURE': 15.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'DOCTOR',
      relatedWords: {
        'HOSPITAL': 5.0,
        'PHYSICIAN': 5.5,
        'MEDICINE': 6.0,
        'MEDICAL': 6.0,
        'NURSE': 6.5,
        'SURGEON': 7.0,
        'HEALTH': 7.0,
        'CLINIC': 7.5,
        'SICK': 8.0,
        'STETHOSCOPE': 8.0,
        'SURGERY': 8.0,
        'PATIENT': 8.5,
        'DIAGNOSIS': 8.5,
        'CURE': 9.0,
        'CHECKUP': 9.0,
        'ILLNESS': 9.5,
        'PRESCRIPTION': 9.5,
        'CARE': 10.0,
        'HEAL': 10.0,
        'DISEASE': 10.0,
        'TREAT': 10.5,
        'PILLS': 11.0,
        'THERAPY': 11.0,
        'REMEDY': 11.5,
        'FEVER': 12.0,
        'PAIN': 12.5,
      },
    ),
    SemanticDistancePuzzle(
      target: 'BREAD',
      relatedWords: {
        'FLOUR': 5.0,
        'LOAF': 5.5,
        'BAKE': 6.0,
        'DOUGH': 6.5,
        'CRUST': 7.0,
        'TOAST': 7.0,
        'SOURDOUGH': 7.0,
        'WHEAT': 7.5,
        'OVEN': 8.0,
        'BAKERY': 8.0,
        'BAGEL': 8.0,
        'RYE': 8.0,
        'KNEAD': 8.0,
        'YEAST': 8.5,
        'BUN': 8.5,
        'SANDWICH': 9.0,
        'ROLL': 9.0,
        'SLICE': 9.5,
        'CROISSANT': 9.5,
        'BUTTER': 10.0,
        'CRUMB': 10.5,
        'GRAIN': 11.0,
        'PASTRY': 11.0,
        'PAN': 12.5,
        'CARB': 13.0,
        'FRESH': 13.5,
        'WARM': 14.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'RIVER',
      relatedWords: {
        'WATER': 4.0,
        'STREAM': 6.0,
        'FLOW': 7.0,
        'BANK': 8.0,
        'CURRENT': 9.0,
        'BOAT': 10.0,
        'BRIDGE': 11.0,
        'FISH': 12.0,
        'LAKE': 13.0,
        'OCEAN': 14.0,
        'VALLEY': 14.5,
        'DELTA': 15.0,
        'CANOE': 15.5,
        'KAYAK': 16.0,
        'RAPIDS': 16.5,
        'FRESHWATER': 17.0,
        'FLOAT': 18.0,
        'SWIM': 19.0,
        'BEND': 20.0,
        'SHORE': 21.0,
        'DAM': 22.0,
        'SOURCE': 23.0,
        'CREEK': 7.5,
        'BROOK': 8.5,
        'ESTUARY': 18.5,
        'TRIBUTARY': 17.5,
        'WAVE': 24.0,
        'BED': 25.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'CLOCK',
      relatedWords: {
        'TIME': 4.0,
        'HOUR': 6.0,
        'MINUTE': 7.0,
        'SECOND': 8.0,
        'WATCH': 8.5,
        'TICK': 9.0,
        'ALARM': 10.0,
        'DIAL': 11.0,
        'HAND': 12.0,
        'DIGITAL': 13.0,
        'PENDULUM': 14.0,
        'TIMER': 14.5,
        'STOPWATCH': 15.0,
        'BELL': 16.0,
        'CHIME': 16.5,
        'WAKE': 17.0,
        'SCHEDULE': 18.0,
        'PUNCTUAL': 19.0,
        'MIDNIGHT': 20.0,
        'NOON': 21.0,
        'WALL': 22.0,
        'GEAR': 23.0,
        'BATTERY': 24.0,
        'DATE': 25.0,
        'CALENDAR': 26.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'HOUSE',
      relatedWords: {
        'HOME': 3.5,
        'ROOM': 6.0,
        'ROOF': 7.0,
        'DOOR': 8.0,
        'WALL': 8.5,
        'WINDOW': 9.0,
        'FLOOR': 10.0,
        'KITCHEN': 11.0,
        'BEDROOM': 11.5,
        'BUILDING': 12.0,
        'FAMILY': 13.0,
        'YARD': 14.0,
        'GARDEN': 14.5,
        'PORCH': 15.0,
        'CHIMNEY': 15.5,
        'LIVING': 16.0,
        'FURNITURE': 17.0,
        'ATTIC': 17.5,
        'BASEMENT': 18.0,
        'BRICK': 19.0,
        'WOOD': 20.0,
        'NEIGHBOR': 21.0,
        'STREET': 22.0,
        'COTTAGE': 13.5,
        'APARTMENT': 15.0,
        'RESIDENCE': 14.0,
        'SHELTER': 16.5,
      },
    ),
    SemanticDistancePuzzle(
      target: 'FLOWER',
      relatedWords: {
        'ROSE': 5.0,
        'PETAL': 6.0,
        'BLOOM': 7.0,
        'GARDEN': 8.0,
        'BLOSSOM': 8.5,
        'STEM': 9.0,
        'PLANT': 10.0,
        'TULIP': 10.5,
        'DAISY': 11.0,
        'BOUQUET': 11.5,
        'SCENT': 12.0,
        'FRAGRANCE': 12.5,
        'BEE': 13.0,
        'POLLEN': 13.5,
        'SUNFLOWER': 14.0,
        'LILY': 14.5,
        'COLOR': 15.0,
        'SPRING': 16.0,
        'FLORIST': 17.0,
        'NATURE': 18.0,
        'LEAF': 19.0,
        'SEED': 20.0,
        'SOIL': 21.0,
        'VASE': 22.0,
        'BEAUTIFUL': 23.0,
        'FLORAL': 11.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'STORM',
      relatedWords: {
        'THUNDER': 4.5,
        'LIGHTNING': 5.0,
        'RAIN': 6.5,
        'WIND': 7.5,
        'TEMPEST': 8.5,
        'HURRICANE': 9.0,
        'TORNADO': 9.5,
        'CLOUD': 10.5,
        'GALE': 11.0,
        'BLIZZARD': 11.5,
        'CYCLONE': 12.0,
        'WEATHER': 13.0,
        'HAIL': 14.0,
        'SQUALL': 14.5,
        'DARK': 16.0,
        'SKY': 17.0,
        'FLASH': 18.0,
        'DAMAGE': 19.0,
        'WARNING': 20.0,
        'RADAR': 21.0,
        'FLOOD': 22.0,
        'COLD': 23.0,
        'POWER': 24.0,
        'CHAOS': 25.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'BIRD',
      relatedWords: {
        'WING': 5.0,
        'FEATHER': 6.0,
        'FLY': 7.0,
        'BEAK': 8.0,
        'NEST': 9.0,
        'EGG': 10.0,
        'SONG': 11.0,
        'EAGLE': 12.0,
        'HAWK': 12.5,
        'ROBIN': 13.0,
        'SPARROW': 13.5,
        'CROW': 14.0,
        'PIGEON': 14.5,
        'CHIRP': 15.0,
        'FLOCK': 15.5,
        'SKY': 16.0,
        'TREE': 17.0,
        'OWL': 17.5,
        'PARROT': 18.0,
        'PERCH': 18.5,
        'AVIAN': 19.0,
        'SOAR': 19.5,
        'WILD': 21.0,
        'ANIMAL': 22.0,
        'BRANCH': 23.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'DOG',
      relatedWords: {
        'PUPPY': 4.0,
        'BARK': 5.5,
        'CANINE': 6.5,
        'PET': 7.0,
        'TAIL': 8.0,
        'PAW': 8.5,
        'BONE': 9.0,
        'COLLAR': 10.0,
        'LEASH': 10.5,
        'HOUND': 11.0,
        'FUR': 12.0,
        'FETCH': 13.0,
        'LOYAL': 13.5,
        'BREED': 14.0,
        'RETRIEVER': 14.5,
        'TERRIER': 15.0,
        'SHEPHERD': 15.5,
        'MUTT': 16.0,
        'KENNEL': 17.0,
        'WALK': 18.0,
        'FRIEND': 19.0,
        'ANIMAL': 20.0,
        'BITE': 21.0,
        'WAG': 11.5,
        'GUARD': 18.5,
      },
    ),
    SemanticDistancePuzzle(
      target: 'CAT',
      relatedWords: {
        'KITTEN': 4.0,
        'MEOW': 5.0,
        'PURR': 6.0,
        'FELINE': 6.5,
        'WHISKER': 7.5,
        'PAW': 8.0,
        'TAIL': 8.5,
        'CLAW': 9.0,
        'FUR': 9.5,
        'PET': 10.0,
        'LITTER': 11.0,
        'SCRATCH': 12.0,
        'NAP': 13.0,
        'MOUSE': 14.0,
        'YARN': 14.5,
        'TABBY': 15.0,
        'SIAMESE': 15.5,
        'LEOPARD': 17.0,
        'TIGER': 17.5,
        'LION': 18.0,
        'ANIMAL': 19.0,
        'SLEEP': 20.0,
        'CALICO': 15.0,
        'HISS': 13.5,
      },
    ),
    SemanticDistancePuzzle(
      target: 'FISH',
      relatedWords: {
        'WATER': 5.0,
        'SWIM': 6.0,
        'FIN': 7.0,
        'GILL': 7.5,
        'SCALE': 8.0,
        'OCEAN': 9.0,
        'SEA': 9.5,
        'RIVER': 10.0,
        'LAKE': 10.5,
        'AQUARIUM': 11.0,
        'HOOK': 12.0,
        'BAIT': 12.5,
        'ANGLER': 13.0,
        'SALMON': 13.5,
        'TUNA': 14.0,
        'TROUT': 14.5,
        'SHARK': 15.0,
        'REEF': 16.0,
        'SEAFOOD': 16.5,
        'NET': 17.0,
        'TANK': 18.0,
        'GOLDFISH': 12.0,
        'CATCH': 19.0,
        'ROD': 20.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'GOLD',
      relatedWords: {
        'SILVER': 5.0,
        'METAL': 6.5,
        'SHINY': 7.5,
        'JEWELRY': 8.5,
        'RING': 9.0,
        'COIN': 9.5,
        'WEALTH': 10.0,
        'RICH': 10.5,
        'MINE': 11.0,
        'NUGGET': 11.5,
        'BULLION': 12.0,
        'TREASURE': 12.5,
        'YELLOW': 13.0,
        'VALUABLE': 13.5,
        'MEDAL': 14.0,
        'INGOT': 14.5,
        'DIAMOND': 15.0,
        'PLATINUM': 15.5,
        'BRONZE': 16.0,
        'VAULT': 17.0,
        'CARAT': 17.5,
        'ORE': 18.0,
        'LUXURY': 19.0,
        'HEIRLOOM': 20.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'BRIDGE',
      relatedWords: {
        'RIVER': 5.0,
        'CROSS': 6.0,
        'ROAD': 7.0,
        'SPAN': 7.5,
        'ARCH': 8.0,
        'SUSPENSION': 9.0,
        'HIGHWAY': 10.0,
        'TRAFFIC': 11.0,
        'BEAM': 12.0,
        'CABLE': 12.5,
        'STEEL': 13.0,
        'CONCRETE': 13.5,
        'PIER': 14.0,
        'OVERPASS': 14.5,
        'CONNECT': 15.0,
        'CROSSING': 15.5,
        'CHANNEL': 16.0,
        'WATER': 17.0,
        'VALLEY': 18.0,
        'ENGINEERING': 19.0,
        'STRUCTURE': 20.0,
        'VIADUCT': 13.0,
        'TOWERS': 16.5,
      },
    ),
    SemanticDistancePuzzle(
      target: 'TRAIN',
      relatedWords: {
        'RAIL': 4.5,
        'TRACK': 5.0,
        'LOCOMOTIVE': 6.0,
        'ENGINE': 7.0,
        'STATION': 7.5,
        'CABOOSE': 8.5,
        'PASSENGER': 9.0,
        'FREIGHT': 9.5,
        'SUBWAY': 10.0,
        'METRO': 10.5,
        'TICKET': 11.0,
        'CAR': 12.0,
        'CONDUCTOR': 12.5,
        'WHISTLE': 13.0,
        'PLATFORM': 13.5,
        'TRANSIT': 14.0,
        'COMMUTE': 15.0,
        'EXPRESS': 15.5,
        'SPEED': 16.0,
        'RAILROAD': 6.5,
        'DEPOT': 14.0,
        'RAILWAY': 5.5,
        'STEAM': 12.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'AIRPLANE',
      relatedWords: {
        'PLANE': 3.0,
        'FLY': 5.0,
        'FLIGHT': 5.5,
        'WING': 6.5,
        'AIRPORT': 7.0,
        'PILOT': 7.5,
        'JET': 8.0,
        'SKY': 8.5,
        'RUNWAY': 9.5,
        'PASSENGER': 10.0,
        'CABIN': 11.0,
        'ALTITUDE': 11.5,
        'COCKPIT': 12.0,
        'AIRLINE': 12.5,
        'LANDING': 13.0,
        'TAKEOFF': 13.5,
        'TERMINAL': 14.0,
        'TURBULENCE': 14.5,
        'AVIATION': 15.0,
        'TRAVEL': 16.0,
        'CREW': 17.0,
        'TICKET': 18.0,
        'LUGGAGE': 19.0,
        'BOEING': 15.5,
      },
    ),
    SemanticDistancePuzzle(
      target: 'MOON',
      relatedWords: {
        'CRATER': 5.0,
        'LUNAR': 5.5,
        'ORBIT': 6.5,
        'NIGHT': 7.0,
        'EARTH': 7.5,
        'TIDE': 8.0,
        'APOLLO': 9.0,
        'ASTRONAUT': 9.5,
        'FULL': 10.0,
        'CRESCENT': 10.5,
        'SPACE': 11.0,
        'ECLIPSE': 11.5,
        'GRAVITY': 12.0,
        'SATELLITE': 12.5,
        'SKY': 13.0,
        'ROCK': 14.0,
        'PHASE': 14.5,
        'LANDING': 15.0,
        'GLOW': 16.0,
        'SILVER': 17.0,
        'LIGHT': 17.5,
        'SURFACE': 18.0,
        'DUST': 19.0,
        'STAR': 20.0,
      },
    ),
    SemanticDistancePuzzle(
      target: 'SUN',
      relatedWords: {
        'SOLAR': 4.5,
        'LIGHT': 5.0,
        'HEAT': 5.5,
        'STAR': 6.0,
        'SHINE': 6.5,
        'DAY': 7.0,
        'BRIGHT': 7.5,
        'RAY': 8.0,
        'SUNSHINE': 8.5,
        'WARMTH': 9.0,
        'MORNING': 10.0,
        'SUNRISE': 10.5,
        'SUNSET': 11.0,
        'EARTH': 11.5,
        'ORBIT': 12.0,
        'FLARE': 12.5,
        'SUMMER': 13.0,
        'ENERGY': 13.5,
        'SPACE': 14.0,
        'BURN': 15.0,
        'CORONA': 15.5,
        'YELLOW': 16.0,
        'SKY': 17.0,
        'GLOW': 17.5,
      },
    ),
    SemanticDistancePuzzle(
      target: 'MONEY',
      relatedWords: {
        'CASH': 4.0,
        'DOLLAR': 5.0,
        'COIN': 5.5,
        'CURRENCY': 6.0,
        'BANK': 6.5,
        'PAY': 7.0,
        'WEALTH': 7.5,
        'RICH': 8.0,
        'WALLET': 8.5,
        'PRICE': 9.0,
        'COST': 9.5,
        'BUY': 10.0,
        'SPEND': 10.5,
        'GOLD': 11.0,
        'BILL': 11.5,
        'CENT': 12.0,
        'SALARY': 12.5,
        'FINANCE': 13.0,
        'ECONOMY': 13.5,
        'INVEST': 14.0,
        'SAVE': 14.5,
        'ATM': 15.0,
        'DEBT': 15.5,
        'CREDIT': 16.0,
        'CHEQUE': 16.5,
      },
    ),
  ];

  String getCluster(String target) => _clusterMap[target] ?? 'GENERAL';

  SemanticDistancePuzzle generatePuzzle() {
    return _puzzles[_random.nextInt(_puzzles.length)];
  }

  double calculateDistance(String target, String guess) {
    guess = guess.toUpperCase().trim();
    if (guess == target) return 0.0;

    if (guess.endsWith('S') && guess.substring(0, guess.length - 1) == target) {
      return 0.5;
    }
    if ('${guess}S' == target) {
      return 0.5;
    }

    final puzzle = _puzzles.firstWhere(
      (p) => p.target == target,
      orElse: () => _puzzles.first,
    );

    if (puzzle.relatedWords.containsKey(guess)) {
      return puzzle.relatedWords[guess]!;
    }

    if (guess.endsWith('S')) {
      final singular = guess.substring(0, guess.length - 1);
      if (puzzle.relatedWords.containsKey(singular)) {
        return puzzle.relatedWords[singular]! + 0.2;
      }
    }

    final plural = '${guess}S';
    if (puzzle.relatedWords.containsKey(plural)) {
      return puzzle.relatedWords[plural]! + 0.2;
    }

    final targetCluster = _clusterMap[target];
    if (targetCluster != null) {
      for (final other in _puzzles) {
        if (other.target != target && _clusterMap[other.target] == targetCluster) {
          if (other.target == guess) {
            return 32.0;
          }
          if (other.relatedWords.containsKey(guess)) {
            final baseDist = other.relatedWords[guess]!;
            return 35.0 + (baseDist * 0.3);
          }
        }
      }
    }

    int hash = guess.codeUnits.fold(0, (prev, element) => prev + element);
    return 50.0 + (hash % 45.0) + (guess.length % 5);
  }
}

class SemanticDistancePuzzle {
  final String target;
  final Map<String, double> relatedWords;

  SemanticDistancePuzzle({
    required this.target,
    required this.relatedWords,
  });
}
