display_name: Puzzle
package_name: puzzle
summary: A collection of brain puzzles.
description: A collection of brain puzzles built with Flutter.
icon: web/icon-512.png
categories:
  - Game
  - LogicGame
