import 'dart:math';

enum VocabularyRelation { synonym, antonym }

class VocabularyQuestion {
  final String word;
  final VocabularyRelation relation;
  final String correctAnswer;
  final List<String> options;

  VocabularyQuestion({
    required this.word,
    required this.relation,
    required this.correctAnswer,
    required this.options,
  });
}

class VocabularyBuilderEngine {
  static final Random _random = Random();

  static const Map<String, List<String>> _synonyms = {
    'Abundant': ['Plentiful', 'Ample', 'Copious'],
    'Accurate': ['Precise', 'Exact', 'Correct'],
    'Active': ['Energetic', 'Lively', 'Busy'],
    'Adaptable': ['Flexible', 'Versatile', 'Adjustable'],
    'Ambitious': ['Aspiring', 'Driven', 'Determined'],
    'Ancient': ['Old', 'Antique', 'Aged'],
    'Brief': ['Short', 'Concise', 'Terse'],
    'Calm': ['Peaceful', 'Serene', 'Tranquil'],
    'Candid': ['Honest', 'Frank', 'Direct'],
    'Cautious': ['Careful', 'Wary', 'Prudent'],
    'Complex': ['Complicated', 'Intricate', 'Involved'],
    'Courageous': ['Brave', 'Valiant', 'Fearless'],
    'Diligent': ['Hardworking', 'Industrious', 'Assiduous'],
    'Distinct': ['Clear', 'Plain', 'Definite'],
    'Eager': ['Enthusiastic', 'Keen', 'Anxious'],
    'Efficient': ['Productive', 'Effective', 'Capable'],
    'Eloquent': ['Articulate', 'Fluent', 'Persuasive'],
    'Fragile': ['Delicate', 'Brittle', 'Frail'],
    'Grateful': ['Thankful', 'Appreciative', 'Obliged'],
    'Hostile': ['Antagonistic', 'Unfriendly', 'Aggressive'],
    'Impartial': ['Fair', 'Unbiased', 'Neutral'],
    'Ingenious': ['Clever', 'Creative', 'Brilliant'],
    'Jovial': ['Cheerful', 'Merry', 'Happy'],
    'Lethargic': ['Sluggish', 'Tired', 'Dull'],
    'Meticulous': ['Thorough', 'Precise', 'Scrupulous'],
    'Obvious': ['Clear', 'Evident', 'Apparent'],
    'Passive': ['Inactive', 'Submissive', 'Yielding'],
    'Plausible': ['Believable', 'Reasonable', 'Credible'],
    'Rigid': ['Stiff', 'Firm', 'Inflexible'],
    'Scarcity': ['Shortage', 'Lack', 'Dearth'],
    'Abandonded': ['Deserted', 'Forsaken', 'Vacant'],
    'Abolish': ['Annul', 'Nullify', 'Cancel'],
    'Abrupt': ['Sudden', 'Hasty', 'Blunt'],
    'Absurd': ['Ridiculous', 'Foolish', 'Ludicrous'],
    'Adversity': ['Misfortune', 'Hardship', 'Trouble'],
    'Aggravate': ['Irritate', 'Exasperate', 'Worsen'],
    'Allure': ['Attract', 'Entice', 'Lure'],
    'Ambiguous': ['Vague', 'Unclear', 'Obscure'],
    'Apathy': ['Indifference', 'Lethargy', 'Detachment'],
    'Arduous': ['Difficult', 'Laborious', 'Strenuous'],
    'Arrogant': ['Haughty', 'Proud', 'Conceited'],
    'Astute': ['Shrewd', 'Clever', 'Insightful'],
    'Authentic': ['Genuine', 'Real', 'True'],
    'Baffle': ['Confuse', 'Perplex', 'Puzzle'],
    'Benevolent': ['Kind', 'Generous', 'Altruistic'],
    'Blatant': ['Obvious', 'Flagrant', 'Glaring'],
    'Boisterous': ['Loud', 'Rowdy', 'Noisy'],
    'Calamity': ['Disaster', 'Catastrophe', 'Tragedy'],
    'Camouflage': ['Disguise', 'Conceal', 'Mask'],
    'Capricious': ['Unpredictable', 'Fickle', 'Impulsive'],
    'Cease': ['Stop', 'Finish', 'Terminate'],
    'Chivalrous': ['Gallant', 'Valiant', 'Courteous'],
    'Coherent': ['Logical', 'Consistent', 'Clear'],
    'Commodious': ['Spacious', 'Roomy', 'Ample'],
    'Compassion': ['Pity', 'Sympathy', 'Empathy'],
    'Complacent': ['Self-satisfied', 'Smug', 'Contented'],
    'Concise': ['Brief', 'Short', 'Succinct'],
    'Condone': ['Excuse', 'Pardon', 'Overlook'],
    'Conspicuous': ['Noticeable', 'Obvious', 'Prominent'],
    'Contemplate': ['Ponder', 'Consider', 'Reflect'],
    'Cordial': ['Friendly', 'Warm', 'Affable'],
    'Cunning': ['Sly', 'Crafty', 'Shrewd'],
    'Dearth': ['Scarcity', 'Shortage', 'Lack'],
    'Deference': ['Respect', 'Esteem', 'Honor'],
    'Deficient': ['Lacking', 'Inadequate', 'Short'],
    'Deleterious': ['Harmful', 'Damaging', 'Injurious'],
    'Demure': ['Modest', 'Shy', 'Reserved'],
    'Depict': ['Portray', 'Describe', 'Represent'],
    'Deride': ['Mock', 'Ridicule', 'Scoff'],
    'Desolate': ['Barren', 'Lonely', 'Empty'],
    'Deteriorate': ['Worsen', 'Decline', 'Degenerate'],
    'Deviate': ['Stray', 'Diverge', 'Depart'],
    'Dexterous': ['Skillful', 'Adept', 'Clever'],
    'Diffident': ['Shy', 'Timid', 'Modest'],
    'Disdain': ['Scorn', 'Contempt', 'Disrespect'],
    'Dormant': ['Inactive', 'Sleeping', 'Latent'],
    'Dubious': ['Doubtful', 'Uncertain', 'Questionable'],
    'Ebullient': ['Enthusiastic', 'Exuberant', 'Cheerful'],
    'Eccentric': ['Odd', 'Unusual', 'Peculiar'],
    'Elaborate': ['Detailed', 'Complex', 'Intricate'],
    'Elusive': ['Evasive', 'Slippery', 'Tricky'],
    'Emancipate': ['Free', 'Liberate', 'Release'],
    'Empower': ['Authorize', 'Enable', 'Permit'],
    'Enigma': ['Mystery', 'Puzzle', 'Riddle'],
    'Ephemeral': ['Short-lived', 'Fleeting', 'Brief'],
    'Epitome': ['Perfect example', 'Essence', 'Ideal'],
    'Equivocal': ['Ambiguous', 'Unclear', 'Vague'],
    'Erudite': ['Learned', 'Scholarly', 'Knowledgeable'],
    'Esoteric': ['Obscure', 'Abstruse', 'Arcane'],
    'Exacerbate': ['Worsen', 'Aggravate', 'Inflame'],
    'Exemplary': ['Commendable', 'Ideal', 'Model'],
    'Exonerate': ['Acquit', 'Absolve', 'Clear'],
    'Exorbitant': ['Excessive', 'Enormous', 'Extreme'],
    'Expedite': ['Hasten', 'Quicken', 'Accelerate'],
    'Explicit': ['Clear', 'Direct', 'Plain'],
    'Extol': ['Praise', 'Laud', 'Acclaim'],
    'Fabricate': ['Construct', 'Manufacture', 'Invent'],
    'Facetious': ['Humorous', 'Jesting', 'Funny'],
    'Fallacy': ['Error', 'Deception', 'Mistake'],
    'Fastidious': ['Particular', 'Demanding', 'Fussy'],
    'Feasible': ['Possible', 'Practical', 'Workable'],
    'Ferocious': ['Fierce', 'Savage', 'Wild'],
    'Fervent': ['Passionate', 'Ardent', 'Enthusiastic'],
    'Flamboyant': ['Showy', 'Flashy', 'Ostentatious'],
    'Flawless': ['Perfect', 'Faultless', 'Immaculate'],
    'Frivolous': ['Trivial', 'Silly', 'Unimportant'],
    'Frugal': ['Economical', 'Thrifty', 'Sparing'],
    'Futile': ['Useless', 'Pointless', 'Vain'],
    'Garrulous': ['Talkative', 'Chatty', 'Loquacious'],
    'Gregarious': ['Sociable', 'Outgoing', 'Friendly'],
    'Gullible': ['Trusting', 'Naive', 'Innocent'],
    'Haphazard': ['Random', 'Disorganized', 'Careless'],
    'Haughty': ['Arrogant', 'Proud', 'Conceited'],
    'Heinous': ['Atrocious', 'Evil', 'Wicked'],
    'Hypocrisy': ['Deceit', 'Insincerity', 'Pretense'],
    'Iconoclast': ['Rebel', 'Maverick', 'Nonconformist'],
    'Idiosyncrasy': ['Peculiarity', 'Quirk', 'Oddity'],
    'Imminent': ['Impending', 'Approaching', 'Nearing'],
    'Immutable': ['Unchangeable', 'Fixed', 'Permanent'],
    'Impetuous': ['Impulsive', 'Rash', 'Hasty'],
    'Incessant': ['Continuous', 'Constant', 'Unending'],
    'Incongruous': ['Inconsistent', 'Absurd', 'Out of place'],
    'Indigenous': ['Native', 'Original', 'Local'],
    'Indolent': ['Lazy', 'Idle', 'Slothful'],
    'Inevitable': ['Unavoidable', 'Certain', 'Sure'],
    'Infallible': ['Faultless', 'Perfect', 'Unerring'],
    'Innate': ['Natural', 'Inborn', 'Inherited'],
    'Innocuous': ['Harmless', 'Safe', 'Innocent'],
    'Insatiable': ['Unquenchable', 'Greedy', 'Voracious'],
    'Inscrutable': ['Mysterious', 'Obscure', 'Unfathomable'],
    'Insipid': ['Bland', 'Dull', 'Tasteless'],
    'Intrepid': ['Brave', 'Bold', 'Fearless'],
    'Invincible': ['Unconquerable', 'Unbeatable', 'Strong'],
    'Irksome': ['Annoying', 'Irritating', 'Tedious'],
    'Judicious': ['Wise', 'Sensible', 'Prudent'],
    'Lament': ['Mourn', 'Grieve', 'Bemoan'],
    'Languid': ['Slow', 'Sluggish', 'Lazy'],
    'Latent': ['Hidden', 'Dormant', 'Inactive'],
    'Laudable': ['Praiseworthy', 'Admirable', 'Creditable'],
    'Lithe': ['Flexible', 'Supple', 'Graceful'],
    'Loquacious': ['Talkative', 'Chatty', 'Garrulous'],
    'Lucid': ['Clear', 'Intelligible', 'Bright'],
    'Magnanimous': ['Generous', 'Noble', 'Kind'],
    'Malevolent': ['Spiteful', 'Wicked', 'Evil'],
    'Mar': ['Spoil', 'Damage', 'Ruin'],
    'Meager': ['Scanty', 'Paltry', 'Small'],
    'Melancholy': ['Sad', 'Gloomy', 'Sorrowful'],
    'Mollify': ['Soothe', 'Calm', 'Pacify'],
    'Mundane': ['Ordinary', 'Boring', 'Common'],
    'Nefarious': ['Wicked', 'Evil', 'Villainous'],
    'Negligent': ['Careless', 'Indifferent', 'Sloppy'],
    'Nocturnal': ['Nightly', 'Dark', 'Night'],
    'Novice': ['Beginner', 'Learner', 'Trainee'],
    'Obscure': ['Vague', 'Unclear', 'Hidden'],
    'Obsolete': ['Outdated', 'Ancient', 'Old'],
    'Obstinate': ['Stubborn', 'Unyielding', 'Headstrong'],
    'Ominous': ['Threatening', 'Sinister', 'Gloomy'],
    'Pacify': ['Calm', 'Soothe', 'Quiet'],
    'Paltry': ['Small', 'Trivial', 'Meager'],
    'Paragon': ['Model', 'Ideal', 'Example'],
    'Partisan': ['Biased', 'Partial', 'One-sided'],
    'Penchant': ['Liking', 'Fondness', 'Tendency'],
    'Pensive': ['Thoughtful', 'Reflective', 'Serious'],
    'Perfunctory': ['Careless', 'Automatic', 'Routine'],
    'Pernicious': ['Harmful', 'Deadly', 'Injurious'],
    'Petulant': ['Irritable', 'Peevish', 'Cranky'],
    'Placid': ['Calm', 'Peaceful', 'Serene'],
    'Plethora': ['Abundance', 'Excess', 'Surplus'],
    'Pliant': ['Flexible', 'Supple', 'Adaptable'],
    'Pragmatic': ['Practical', 'Realistic', 'Down-to-earth'],
    'Precarious': ['Uncertain', 'Unstable', 'Dangerous'],
    'Precocious': ['Gifted', 'Advanced', 'Bright'],
    'Pretentious': ['Showy', 'Flashy', 'Pompous'],
    'Prudent': ['Wise', 'Careful', 'Cautions'],
    'Pungent': ['Sharp', 'Strong', 'Stinging'],
    'Quaint': ['Charming', 'Odd', 'Old-fashioned'],
    'Rancor': ['Resentment', 'Hatred', 'Ill-will'],
    'Reciprocal': ['Mutual', 'Joint', 'Shared'],
    'Refute': ['Disprove', 'Deny', 'Contradict'],
    'Reiterate': ['Repeat', 'Restate', 'Recap'],
    'Relinquish': ['Give up', 'Abandon', 'Surrender'],
    'Remorse': ['Regret', 'Guilt', 'Pity'],
    'Resilient': ['Strong', 'Tough', 'Flexible'],
    'Reticent': ['Quiet', 'Reserved', 'Shy'],
    'Revere': ['Respect', 'Honor', 'Admire'],
    'Robust': ['Strong', 'Healthy', 'Sturdy'],
    'Sagacious': ['Wise', 'Clever', 'Shrewd'],
    'Satiate': ['Satisfy', 'Fill', 'Surfeit'],
    'Scrupulous': ['Meticulous', 'Thorough', 'Honest'],
    'Serene': ['Calm', 'Peaceful', 'Quiet'],
    'Sporadic': ['Occasional', 'Irregular', 'Random'],
    'Stoic': ['Indifferent', 'Unemotional', 'Patient'],
    'Strenuous': ['Difficult', 'Arduous', 'Tough'],
    'Submissive': ['Obedient', 'Passive', 'Yielding'],
    'Succinct': ['Brief', 'Short', 'Concise'],
    'Superficial': ['Shallow', 'Slight', 'Surface'],
    'Surplus': ['Excess', 'Abundance', 'Extra'],
    'Taciturn': ['Quiet', 'Reserved', 'Silent'],
    'Tenuous': ['Weak', 'Fragile', 'Thin'],
    'Terse': ['Brief', 'Short', 'Concise'],
    'Timorous': ['Fearful', 'Shy', 'Timid'],
    'Tranquil': ['Peaceful', 'Calm', 'Quiet'],
    'Transient': ['Temporary', 'Brief', 'Passing'],
    'Trivial': ['Unimportant', 'Slight', 'Small'],
    'Ubiquitous': ['Omnipresent', 'Everywhere', 'Pervasive'],
    'Uncouth': ['Rude', 'Clumsy', 'Boorish'],
    'Urbane': ['Sophisticated', 'Polished', 'Refined'],
    'Vacillate': ['Waver', 'Hesitate', 'Dither'],
    'Venerate': ['Respect', 'Honor', 'Revere'],
    'Verbose': ['Wordy', 'Talkative', 'Long-winded'],
    'Versatile': ['Adaptable', 'Flexible', 'All-around'],
    'Vex': ['Annoy', 'Irritate', 'Bother'],
    'Vibrant': ['Energetic', 'Lively', 'Vivid'],
    'Vigilant': ['Watchful', 'Alert', 'Careful'],
    'Vilify': ['Slander', 'Defame', 'Malign'],
    'Vindication': ['Justification', 'Proof', 'Defense'],
    'Vindictive': ['Spiteful', 'Revengeful', 'Mean'],
    'Virtuoso': ['Expert', 'Master', 'Genius'],
    'Volatile': ['Unstable', 'Explosive', 'Changeable'],
    'Voracious': ['Greedy', 'Insatiable', 'Hungry'],
    'Wary': ['Cautious', 'Careful', 'Watchful'],
    'Whimsical': ['Playful', 'Fanciful', 'Odd'],
    'Wily': ['Cunning', 'Sly', 'Crafty'],
    'Zealous': ['Enthusiastic', 'Passionate', 'Eager'],
    'Zenith': ['Peak', 'Top', 'Summit'],
  };

  static const Map<String, List<String>> _antonyms = {
    'Abundant': ['Scarce', 'Meager', 'Sparse'],
    'Accurate': ['Inaccurate', 'Wrong', 'Incorrect'],
    'Active': ['Passive', 'Idle', 'Lazy'],
    'Ancient': ['Modern', 'New', 'Recent'],
    'Brief': ['Long', 'Extended', 'Lengthy'],
    'Calm': ['Agitated', 'Turbulent', 'Stormy'],
    'Candid': ['Deceptive', 'Evasive', 'Secretive'],
    'Cautious': ['Reckless', 'Rash', 'Bold'],
    'Complex': ['Simple', 'Easy', 'Plain'],
    'Courageous': ['Cowardly', 'Fearful', 'Timid'],
    'Diligent': ['Lazy', 'Negligent', 'Idle'],
    'Distinct': ['Vague', 'Faint', 'Unclear'],
    'Eager': ['Indifferent', 'Apathetic', 'Uninterested'],
    'Efficient': ['Inefficient', 'Wasteful', 'Incompetent'],
    'Fragile': ['Sturdy', 'Strong', 'Tough'],
    'Grateful': ['Ungrateful', 'Unthankful', 'Thankless'],
    'Hostile': ['Friendly', 'Kind', 'Amiable'],
    'Impartial': ['Biased', 'Partial', 'Prejudiced'],
    'Ingenious': ['Foolish', 'Simple', 'Stupid'],
    'Jovial': ['Miserable', 'Gloomy', 'Sad'],
    'Lethargic': ['Energetic', 'Active', 'Vibrant'],
    'Meticulous': ['Careless', 'Sloppy', 'Messy'],
    'Obvious': ['Hidden', 'Obscure', 'Unclear'],
    'Plausible': ['Improbable', 'Unlikely', 'Unbelievable'],
    'Rigid': ['Flexible', 'Pliant', 'Soft'],
    'Abolish': ['Establish', 'Create', 'Support'],
    'Abrupt': ['Gradual', 'Slow', 'Gentle'],
    'Absurd': ['Logical', 'Sensible', 'Reasonable'],
    'Adversity': ['Prosperity', 'Success', 'Fortune'],
    'Aggravate': ['Soothe', 'Calm', 'Alleviate'],
    'Allure': ['Repel', 'Deter', 'Disgust'],
    'Ambiguous': ['Clear', 'Definite', 'Explicit'],
    'Apathy': ['Enthusiasm', 'Interest', 'Concern'],
    'Arduous': ['Easy', 'Effortless', 'Simple'],
    'Arrogant': ['Humble', 'Modest', 'Meek'],
    'Astute': ['Foolish', 'Stupid', 'Naive'],
    'Authentic': ['Fake', 'False', 'Counterfeit'],
    'Benevolent': ['Malevolent', 'Cruel', 'Selfish'],
    'Blatant': ['Subtle', 'Hidden', 'Inconspicuous'],
    'Boisterous': ['Quiet', 'Calm', 'Silent'],
    'Calamity': ['Blessing', 'Fortune', 'Success'],
    'Capricious': ['Steady', 'Consistent', 'Reliable'],
    'Cease': ['Begin', 'Start', 'Continue'],
    'Chivalrous': ['Rude', 'Cowardly', 'Uncivil'],
    'Coherent': ['Incoherent', 'Confused', 'Illogical'],
    'Commodious': ['Cramped', 'Small', 'Narrow'],
    'Compassion': ['Cruelty', 'Indifference', 'Hatred'],
    'Complacent': ['Anxious', 'Dissatisfied', 'Ambitious'],
    'Concise': ['Verbose', 'Wordy', 'Long'],
    'Condone': ['Condemn', 'Punish', 'Forbid'],
    'Conspicuous': ['Hidden', 'Subtle', 'Vague'],
    'Cordial': ['Hostile', 'Cold', 'Unfriendly'],
    'Cunning': ['Naive', 'Simple', 'Honest'],
    'Dearth': ['Abundance', 'Surplus', 'Plenty'],
    'Deference': ['Disrespect', 'Disdain', 'Scorn'],
    'Deficient': ['Sufficient', 'Adequate', 'Full'],
    'Deleterious': ['Beneficial', 'Helpful', 'Healthy'],
    'Demure': ['Bold', 'Outgoing', 'Aggressive'],
    'Deride': ['Praise', 'Applaud', 'Honor'],
    'Desolate': ['Populated', 'Lively', 'Full'],
    'Deteriorate': ['Improve', 'Enhance', 'Build'],
    'Deviate': ['Follow', 'Conform', 'Stay'],
    'Dexterous': ['Clumsy', 'Awkward', 'Inept'],
    'Diffident': ['Confident', 'Bold', 'Self-assured'],
    'Disdain': ['Respect', 'Admiration', 'Esteem'],
    'Dormant': ['Active', 'Lively', 'Awake'],
    'Dubious': ['Certain', 'Sure', 'Reliable'],
    'Ebullient': ['Depressed', 'Gloomy', 'Unhappy'],
    'Eccentric': ['Normal', 'Ordinary', 'Common'],
    'Elusive': ['Obvious', 'Plain', 'Stable'],
    'Emancipate': ['Enslave', 'Bind', 'Restrain'],
    'Ephemeral': ['Permanent', 'Eternal', 'Lasting'],
    'Erudite': ['Ignorant', 'Uneducated', 'Illiterate'],
    'Exacerbate': ['Improve', 'Soften', 'Help'],
    'Exemplary': ['Poor', 'Bad', 'Unworthy'],
    'Exonerate': ['Convict', 'Blame', 'Charge'],
    'Exorbitant': ['Cheap', 'Low', 'Moderate'],
    'Expedite': ['Delay', 'Hinder', 'Slow'],
    'Explicit': ['Vague', 'Implicit', 'Hidden'],
    'Extol': ['Criticize', 'Blame', 'Condemn'],
    'Fastidious': ['Easygoing', 'Careless', 'Indifferent'],
    'Feasible': ['Impossible', 'Unworkable', 'Impractical'],
    'Ferocious': ['Gentle', 'Tame', 'Mild'],
    'Fervent': ['Apathetic', 'Cold', 'Indifferent'],
    'Flamboyant': ['Plain', 'Simple', 'Modest'],
    'Flawless': ['Defective', 'Imperfect', 'Flawed'],
    'Frivolous': ['Serious', 'Important', 'Solemn'],
    'Frugal': ['Extravagant', 'Wasteful', 'Lavish'],
    'Futile': ['Effective', 'Useful', 'Helpful'],
    'Garrulous': ['Silent', 'Quiet', 'Reserved'],
    'Gregarious': ['Introverted', 'Shy', 'Antisocial'],
    'Haphazard': ['Planned', 'Orderly', 'Systematic'],
    'Heinous': ['Good', 'Wonderful', 'Admirable'],
    'Immutable': ['Variable', 'Flexible', 'Changing'],
    'Impetuous': ['Cautions', 'Careful', 'Thoughtful'],
    'Incessant': ['Occasional', 'Intermittent', 'Broken'],
    'Indigenous': ['Foreign', 'Alien', 'Exotic'],
    'Indolent': ['Energetic', 'Active', 'Hardworking'],
    'Inevitable': ['Unlikely', 'Uncertain', 'Avoidable'],
    'Infallible': ['Fallible', 'Imperfect', 'Unreliable'],
    'Innate': ['Learned', 'Acquired', 'Foreign'],
    'Innocuous': ['Harmful', 'Dangerous', 'Toxic'],
    'Insipid': ['Tasty', 'Flavorful', 'Exciting'],
    'Intrepid': ['Fearful', 'Cowardly', 'Timid'],
    'Invincible': ['Vulnerable', 'Weak', 'Fragile'],
    'Irksome': ['Pleasant', 'Enjoyable', 'Delightful'],
    'Judicious': ['Foolish', 'Rash', 'Imprudent'],
    'Languid': ['Vigorous', 'Energetic', 'Active'],
    'Latent': ['Active', 'Evident', 'Clear'],
    'Laudable': ['Blameworthy', 'Bad', 'Poor'],
    'Lithe': ['Stiff', 'Rigid', 'Clumsy'],
    'Lucid': ['Confused', 'Vague', 'Dark'],
    'Magnanimous': ['Selfish', 'Mean', 'Small'],
    'Malevolent': ['Benevolent', 'Kind', 'Friendly'],
    'Meager': ['Abundant', 'Plenty', 'Large'],
    'Melancholy': ['Happy', 'Cheerful', 'Joyful'],
    'Mundane': ['Extraordinary', 'Exciting', 'Unique'],
    'Nefarious': ['Good', 'Righteous', 'Virtuous'],
    'Negligent': ['Careful', 'Attentive', 'Diligent'],
    'Novice': ['Expert', 'Professional', 'Veteran'],
    'Obsolete': ['Modern', 'New', 'Current'],
    'Obstinate': ['Flexible', 'Compliant', 'Yielding'],
    'Ominous': ['Promising', 'Hopeful', 'Bright'],
    'Paltry': ['Substantial', 'Large', 'Significant'],
    'Partisan': ['Unbiased', 'Neutral', 'Fair'],
    'Pernicious': ['Beneficial', 'Helpful', 'Safe'],
    'Petulant': ['Good-humored', 'Patient', 'Calm'],
    'Placid': ['Agitated', 'Wild', 'Stormy'],
    'Plethora': ['Scarcity', 'Lack', 'Shortage'],
    'Pragmatic': ['Idealistic', 'Unrealistic', 'Dreamy'],
    'Precarious': ['Safe', 'Secure', 'Stable'],
    'Precocious': ['Backward', 'Slow', 'Average'],
    'Pretentious': ['Humble', 'Simple', 'Modest'],
    'Prudent': ['Reckless', 'Foolish', 'Rash'],
    'Pungent': ['Bland', 'Mild', 'Weak'],
    'Quaint': ['Modern', 'New', 'Common'],
    'Rancor': ['Love', 'Friendship', 'Kindness'],
    'Reciprocal': ['One-sided', 'Independent', 'Separate'],
    'Refute': ['Prove', 'Confirm', 'Support'],
    'Relinquish': ['Keep', 'Hold', 'Retain'],
    'Remorse': ['Pride', 'Satisfaction', 'Indifference'],
    'Resilient': ['Fragile', 'Weak', 'Vulnerable'],
    'Reticent': ['Talkative', 'Outgoing', 'Chatty'],
    'Robust': ['Weak', 'Fragile', 'Sickly'],
    'Sagacious': ['Foolish', 'Ignorant', 'Stupid'],
    'Scrupulous': ['Dishonest', 'Careless', 'Corrupt'],
    'Serene': ['Anxious', 'Troubled', 'Stormy'],
    'Stoic': ['Emotional', 'Sensitive', 'Weak'],
    'Strenuous': ['Easy', 'Light', 'Effortless'],
    'Submissive': ['Rebellious', 'Defiant', 'Strong'],
    'Succinct': ['Wordy', 'Verbose', 'Lengthy'],
    'Superficial': ['Deep', 'Thorough', 'Profound'],
    'Taciturn': ['Talkative', 'Loquacious', 'Chatty'],
    'Timorous': ['Bold', 'Brave', 'Confident'],
    'Tranquil': ['Noisy', 'Busy', 'Wild'],
    'Transient': ['Permanent', 'Lasting', 'Eternal'],
    'Trivial': ['Important', 'Vital', 'Significant'],
    'Uncouth': ['Refined', 'Polite', 'Sophisticated'],
    'Urbane': ['Unrefined', 'Crude', 'Boorish'],
    'Vacillate': ['Decide', 'Resolve', 'Stay'],
    'Verbose': ['Brief', 'Concise', 'Silent'],
    'Vex': ['Please', 'Soothe', 'Delight'],
    'Vibrant': ['Dull', 'Lifeless', 'Pale'],
    'Vigilant': ['Careless', 'Negligent', 'Asleep'],
    'Vilify': ['Honor', 'Praise', 'Glorify'],
    'Vindictive': ['Forgiving', 'Merciful', 'Kind'],
    'Volatile': ['Stable', 'Calm', 'Fixed'],
    'Voracious': ['Full', 'Satisfied', 'Indifferent'],
    'Wary': ['Trusting', 'Rash', 'Careless'],
    'Zealous': ['Apathetic', 'Indifferent', 'Lazy'],
    'Zenith': ['Nadir', 'Bottom', 'Base'],
  };

  static VocabularyQuestion generateQuestion(String difficulty) {
    bool useSynonym = _random.nextBool();
    VocabularyRelation relation = useSynonym ? VocabularyRelation.synonym : VocabularyRelation.antonym;
    Map<String, List<String>> dataSource = useSynonym ? _synonyms : _antonyms;
    Map<String, List<String>> wrongSource = useSynonym ? _antonyms : _synonyms;

    List<String> keys = dataSource.keys.toList();
    String word = keys[_random.nextInt(keys.length)];
    List<String> correctOptions = dataSource[word]!;
    String correctAnswer = correctOptions[_random.nextInt(correctOptions.length)];

    List<String> options = [correctAnswer];
    
    // Fill with wrong answers
    while (options.length < 4) {
      String wrongWord;
      if (_random.nextBool() && wrongSource.containsKey(word)) {
        // Use an actual antonym as a wrong answer for a synonym question (and vice versa)
        List<String> wrongOptions = wrongSource[word]!;
        wrongWord = wrongOptions[_random.nextInt(wrongOptions.length)];
      } else {
        // Use a random word from the other source
        String randomKey = keys[_random.nextInt(keys.length)];
        List<String> randomOptions = dataSource[randomKey]!;
        wrongWord = randomOptions[_random.nextInt(randomOptions.length)];
      }

      if (!options.contains(wrongWord)) {
        options.add(wrongWord);
      }
    }

    options.shuffle();

    return VocabularyQuestion(
      word: word,
      relation: relation,
      correctAnswer: correctAnswer,
      options: options,
    );
  }
}
