import 'dart:math';

enum PartOfSpeech { noun, verb, adjective }

class GrammarWord {
  final String word;
  final PartOfSpeech type;

  GrammarWord(this.word, this.type);
}

class GrammarSortEngine {
  final Random _random = Random();

  final List<GrammarWord> _words = [
    // Nouns
    GrammarWord('MOUNTAIN', PartOfSpeech.noun),
    GrammarWord('COMPUTER', PartOfSpeech.noun),
    GrammarWord('HOSPITAL', PartOfSpeech.noun),
    GrammarWord('ELEPHANT', PartOfSpeech.noun),
    GrammarWord('LIBRARY', PartOfSpeech.noun),
    GrammarWord('FRIENDSHIP', PartOfSpeech.noun),
    GrammarWord('OCEAN', PartOfSpeech.noun),
    GrammarWord('GALAXY', PartOfSpeech.noun),
    GrammarWord('CHAIR', PartOfSpeech.noun),
    GrammarWord('PIZZA', PartOfSpeech.noun),
    GrammarWord('RIVER', PartOfSpeech.noun),
    GrammarWord('SUNSET', PartOfSpeech.noun),
    GrammarWord('BICYCLE', PartOfSpeech.noun),
    GrammarWord('DOLPHIN', PartOfSpeech.noun),
    GrammarWord('BLANKET', PartOfSpeech.noun),
    GrammarWord('LANTERN', PartOfSpeech.noun),
    GrammarWord('VOLCANO', PartOfSpeech.noun),
    GrammarWord('ACORN', PartOfSpeech.noun),
    GrammarWord('TROPHY', PartOfSpeech.noun),
    GrammarWord('BRIDGE', PartOfSpeech.noun),
    GrammarWord('CANDLE', PartOfSpeech.noun),
    GrammarWord('DIAMOND', PartOfSpeech.noun),
    GrammarWord('FEATHER', PartOfSpeech.noun),
    GrammarWord('ISLAND', PartOfSpeech.noun),
    GrammarWord('JACKET', PartOfSpeech.noun),
    GrammarWord('KITCHEN', PartOfSpeech.noun),
    GrammarWord('PENCIL', PartOfSpeech.noun),
    GrammarWord('ROBOT', PartOfSpeech.noun),
    GrammarWord('SPIDER', PartOfSpeech.noun),
    GrammarWord('TURTLE', PartOfSpeech.noun),
    GrammarWord('UMBRELLA', PartOfSpeech.noun),
    GrammarWord('VIOLIN', PartOfSpeech.noun),
    GrammarWord('WALRUS', PartOfSpeech.noun),
    GrammarWord('BASKET', PartOfSpeech.noun),
    GrammarWord('CACTUS', PartOfSpeech.noun),
    GrammarWord('CROWN', PartOfSpeech.noun),
    GrammarWord('MARBLE', PartOfSpeech.noun),
    GrammarWord('BRANCH', PartOfSpeech.noun),
    GrammarWord('LADDER', PartOfSpeech.noun),
    GrammarWord('GARDEN', PartOfSpeech.noun),
    GrammarWord('HAMMER', PartOfSpeech.noun),
    GrammarWord('NEST', PartOfSpeech.noun),
    GrammarWord('PIANO', PartOfSpeech.noun),
    GrammarWord('BUCKET', PartOfSpeech.noun),
    // Verbs
    GrammarWord('EXPLORE', PartOfSpeech.verb),
    GrammarWord('CELEBRATE', PartOfSpeech.verb),
    GrammarWord('NAVIGATE', PartOfSpeech.verb),
    GrammarWord('BAKE', PartOfSpeech.verb),
    GrammarWord('CREATE', PartOfSpeech.verb),
    GrammarWord('TICKLE', PartOfSpeech.verb),
    GrammarWord('WANDER', PartOfSpeech.verb),
    GrammarWord('EXAMINE', PartOfSpeech.verb),
    GrammarWord('UNLOCK', PartOfSpeech.verb),
    GrammarWord('IMAGINE', PartOfSpeech.verb),
    GrammarWord('BELIEVE', PartOfSpeech.verb),
    GrammarWord('BRING', PartOfSpeech.verb),
    GrammarWord('CHOOSE', PartOfSpeech.verb),
    GrammarWord('COMPARE', PartOfSpeech.verb),
    GrammarWord('DECIDE', PartOfSpeech.verb),
    GrammarWord('DISCOVER', PartOfSpeech.verb),
    GrammarWord('ENCOURAGE', PartOfSpeech.verb),
    GrammarWord('EXPLAIN', PartOfSpeech.verb),
    GrammarWord('FOLLOW', PartOfSpeech.verb),
    GrammarWord('FORGIVE', PartOfSpeech.verb),
    GrammarWord('GATHER', PartOfSpeech.verb),
    GrammarWord('GROW', PartOfSpeech.verb),
    GrammarWord('INVENT', PartOfSpeech.verb),
    GrammarWord('LISTEN', PartOfSpeech.verb),
    GrammarWord('OBEY', PartOfSpeech.verb),
    GrammarWord('PERFORM', PartOfSpeech.verb),
    GrammarWord('PREVENT', PartOfSpeech.verb),
    GrammarWord('PROTECT', PartOfSpeech.verb),
    GrammarWord('RECEIVE', PartOfSpeech.verb),
    GrammarWord('REMEMBER', PartOfSpeech.verb),
    GrammarWord('REQUIRE', PartOfSpeech.verb),
    GrammarWord('SOLVE', PartOfSpeech.verb),
    GrammarWord('SURVIVE', PartOfSpeech.verb),
    GrammarWord('TEACH', PartOfSpeech.verb),
    GrammarWord('UNDERSTAND', PartOfSpeech.verb),
    GrammarWord('WARN', PartOfSpeech.verb),
    GrammarWord('ADD', PartOfSpeech.verb),
    GrammarWord('ARRIVE', PartOfSpeech.verb),
    GrammarWord('BEHAVE', PartOfSpeech.verb),
    GrammarWord('BELONG', PartOfSpeech.verb),
    GrammarWord('BORROW', PartOfSpeech.verb),
    GrammarWord('BREATHE', PartOfSpeech.verb),
    GrammarWord('BURN', PartOfSpeech.verb),
    // Adjectives
    GrammarWord('BEAUTIFUL', PartOfSpeech.adjective),
    GrammarWord('BRILLIANT', PartOfSpeech.adjective),
    GrammarWord('NOISY', PartOfSpeech.adjective),
    GrammarWord('ENERGETIC', PartOfSpeech.adjective),
    GrammarWord('MYSTERIOUS', PartOfSpeech.adjective),
    GrammarWord('GIGANTIC', PartOfSpeech.adjective),
    GrammarWord('FRAGILE', PartOfSpeech.adjective),
    GrammarWord('SUCCESSFUL', PartOfSpeech.adjective),
    GrammarWord('SPICY', PartOfSpeech.adjective),
    GrammarWord('DILIGENT', PartOfSpeech.adjective),
    GrammarWord('TALL', PartOfSpeech.adjective),
    GrammarWord('WARM', PartOfSpeech.adjective),
    GrammarWord('CRISPY', PartOfSpeech.adjective),
    GrammarWord('SAD', PartOfSpeech.adjective),
    GrammarWord('ANGRY', PartOfSpeech.adjective),
    GrammarWord('GLAD', PartOfSpeech.adjective),
    GrammarWord('LAZY', PartOfSpeech.adjective),
    GrammarWord('NEAT', PartOfSpeech.adjective),
    GrammarWord('NICE', PartOfSpeech.adjective),
    GrammarWord('PURE', PartOfSpeech.adjective),
    GrammarWord('TINY', PartOfSpeech.adjective),
    GrammarWord('EAGER', PartOfSpeech.adjective),
    GrammarWord('GENTLE', PartOfSpeech.adjective),
    GrammarWord('HAPPY', PartOfSpeech.adjective),
    GrammarWord('HUNGRY', PartOfSpeech.adjective),
    GrammarWord('JEALOUS', PartOfSpeech.adjective),
    GrammarWord('LONELY', PartOfSpeech.adjective),
    GrammarWord('POLITE', PartOfSpeech.adjective),
    GrammarWord('RURAL', PartOfSpeech.adjective),
    GrammarWord('SERIOUS', PartOfSpeech.adjective),
    GrammarWord('SILENT', PartOfSpeech.adjective),
    GrammarWord('THIRSTY', PartOfSpeech.adjective),
    GrammarWord('VAST', PartOfSpeech.adjective),
    GrammarWord('WORRIED', PartOfSpeech.adjective),
    GrammarWord('COLD', PartOfSpeech.adjective),
    GrammarWord('COOL', PartOfSpeech.adjective),
    GrammarWord('FUZZY', PartOfSpeech.adjective),
    GrammarWord('MERRY', PartOfSpeech.adjective),
    GrammarWord('RARE', PartOfSpeech.adjective),
    GrammarWord('SEVERE', PartOfSpeech.adjective),
    GrammarWord('AGILE', PartOfSpeech.adjective),
    GrammarWord('BLAND', PartOfSpeech.adjective),
    GrammarWord('BOLD', PartOfSpeech.adjective),
  ];

  GrammarWord nextWord() {
    return _words[_random.nextInt(_words.length)];
  }
}
