display_name: Puzzle
package_name: com-sidhant-puzzle
maintainer:
  name: Sidhant
  email: sidhant@example.com
summary: A collection of brain puzzles.
description: A collection of brain puzzles built with Flutter.
icon: web/icon-512.png
categories:
  - Game
  - LogicGame
priority: optional
section: games
architecture: amd64
installed_size: 100
