name: puzzle-games
base: core22
version: '1.0.13'
summary: A professional suite of minimalist puzzle games
description: |
  A professional suite of minimalist puzzle games.

confinement: strict
grade: stable

apps:
  puzzle-games:
    command: puzzle
    extensions: [gnome]
    desktop: gui/com.sidhant.puzzle.desktop
    plugs:
      - home

parts:
  puzzle:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    flutter-channel: stable
    build-packages:
      - libgtk-3-dev
      - liblzma-dev
      - pkg-config
  metadata:
    plugin: dump
    source: snap/local
    organize:
      com.sidhant.puzzle.metainfo.xml: usr/share/metainfo/com.sidhant.puzzle.metainfo.xml
