name: Snap Build Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: snapcore/action-build@v1
        id: snapcraft

      - uses: actions/upload-artifact@v4
        with:
          name: snap-artifact
          path: ${{ steps.snapcraft.outputs.snap }}


